MARORKA_USERNAME = "reports@technomar.gr"
MARORKA_PASSWORD = "Technomar123!"
MARORKA_AUTH_METHOD = "digest"
MARORKA_TOKEN = ""
DASHBOARD_PASSWORD = "1341924"
DASHBOARD_BACKGROUND_IMAGE = "mantalos-nikolic-960x540.webp"
